apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    run: lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: lb